# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/HP/AppData/Local/Programs/Python/Python39/Lib/site-packages/PyQt5/Qt/plugins/platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 180, 71, 31))
        self.label_2.setObjectName("label_2")
        self.Plaintext_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.Plaintext_txt.setGeometry(QtCore.QRect(310, 140, 471, 71))
        self.Plaintext_txt.setObjectName("Plaintext_txt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Encrypt_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt_Button.setGeometry(QtCore.QRect(360, 470, 75, 23))
        self.Encrypt_Button.setObjectName("Encrypt_Button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 350, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 270, 71, 31))
        self.label_3.setObjectName("label_3")
        self.key_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.key_txt.setGeometry(QtCore.QRect(310, 260, 471, 41))
        self.key_txt.setObjectName("key_txt")
        self.CipherText_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.CipherText_txt.setGeometry(QtCore.QRect(310, 340, 471, 61))
        self.CipherText_txt.setObjectName("CipherText_txt")
        self.Decrypt_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt_Button.setGeometry(QtCore.QRect(600, 470, 75, 23))
        self.Decrypt_Button.setObjectName("Decrypt_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher - caesar.ui"))
        self.label_2.setText(_translate("MainWindow", "Plaint Text :"))
        self.label.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.Encrypt_Button.setText(_translate("MainWindow", "Encrypt"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text: "))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.Decrypt_Button.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
