# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Gen_btn.setGeometry(QtCore.QRect(510, 100, 91, 23))
        self.Gen_btn.setObjectName("Gen_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 160, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Sign_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Sign_btn.setGeometry(QtCore.QRect(270, 420, 75, 23))
        self.Sign_btn.setObjectName("Sign_btn")
        self.Verify_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Verify_btn.setGeometry(QtCore.QRect(370, 420, 75, 23))
        self.Verify_btn.setObjectName("Verify_btn")
        self.Infor_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Infor_txt.setGeometry(QtCore.QRect(230, 160, 371, 71))
        self.Infor_txt.setObjectName("Infor_txt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 280, 61, 21))
        self.label_5.setObjectName("label_5")
        self.Sig_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Sig_txt.setGeometry(QtCore.QRect(230, 280, 371, 71))
        self.Sig_txt.setObjectName("Sig_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gen_btn.setText(_translate("MainWindow", "Generate Keys"))
        self.label_4.setText(_translate("MainWindow", "Infomation"))
        self.label_3.setText(_translate("MainWindow", "ECC CIPHER"))
        self.Sign_btn.setText(_translate("MainWindow", "Sign"))
        self.Verify_btn.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
